# Generated by Django 3.2.1 on 2021-10-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('fathers_name', models.CharField(max_length=200, null=True)),
                ('dob', models.DateField(null=True)),
                ('Address', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=20, null=True)),
                ('pin', models.IntegerField(max_length=7, null=True)),
                ('phone_no', models.IntegerField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('class_opted', models.IntegerField(max_length=2)),
                ('marks', models.IntegerField(max_length=3, null=True, verbose_name='Marks%')),
                ('date_enrolled', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
